local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "Website/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    folder: "site/pages"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }

